# Generated by Django 2.0.3 on 2018-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=140)),
                ('tweet_language', models.CharField(max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
